### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by CharlesFeng207** [Unity-Technologies/Animation-Instancing#1]
I opened the Crowd Simulation scene in your project. when I try to run it, there is an error:
![image](https://user-images.githubusercontent.com/26399130/37452336-3d36cd10-286f-11e8-8b18-86058cce6928.png)
after that I saw a lot of characters instantiated but couldn't appear in game windows.
(in unity 2018.1.0b9 on Win10,)

**Comment by jeremyfpope** [comment]
@CharlesFeng207  Try selecting Custom Editor -> AssetBundle -> BuildAssetBundle (Platform).  Worked for me on PC using 5.6.0f3.

**Comment by CloudJin** [comment]
Yes. You need to build the asset bundle at first. I don't commit them because I can't make sure which platform you used.

**Comment by laurentopia** [comment]
How is asset bundle needed for this tech demo? Took a quick look and I don't see where the GPU animation instancing depends on asset pipeline stuff.

**Comment by CloudJin** [comment]
@laurentopia , yes, you're right. This is not necessary. As a Unityer, I suggest to use asset bundle to make games. But it's easy to do without asset bundle. I will twink it as soon as I can.
