### ISSUE TITLE
使用不同材质球的多个skinnedMeshRenderer导出后，顶点位置有奇怪的偏移

### ISSUE THREAD

**Issue by cg4213** [Unity-Technologies/Animation-Instancing#11]
我角色的头和衣服是两个材质球，转化之后头飘起来了。看起来动画骨骼的计算也在生效
IOS，Animation
呃，有没有可能是我的Animation生成数据的地方有问题？会是什么问题呢？

**Comment by CloudJin** [comment]
方便把你的asset上传一下吗？我来查一下具体是什么问题。

**Comment by cg4213** [comment]
[AnimationInstancing.zip](https://github.com/Unity-Technologies/Animation-Instancing/files/1978303/AnimationInstancing.zip)
这样就可以吧？

**Comment by zhouyufan0568** [comment]
相同bug+1

**Comment by CloudJin** [comment]
收到。我正在查找具体是什么问题。
