### ISSUE TITLE
可以支持多个camera，改变layer的情况吗？

### ISSUE THREAD

**Issue by chbin12** [Unity-Technologies/Animation-Instancing#13]
如题，因为我们项目中是2d场景+3d角色的处理，需要对角色在不同情况下修改layer让不同的camera渲染，目前好象不支持这种情况，不知道有办法支持吗？
还有个现象：我用正交camera，改变size时，角色移动时会留下残影，如图
谢谢
![image](https://user-images.githubusercontent.com/14818668/39698107-ffe4a96a-5225-11e8-801d-99e7010b6b41.png)

**Comment by CloudJin** [comment]
目前确实没有支持，所有的角色都渲染在layer 0上了。
对于layer的支持我回头会添加上的。

残影的这个问题我没有重现出来，请问怎么重现呢？

**Comment by chbin12** [comment]
我昨天在你的demo里重现了类似的现象，如下方法可以重现
1.把prefab的applyRootMotion勾除掉；
2.修改RandomCharacters的第72和82行增加如下代码，目的是为了让角色移动动起来
				if(!instancing.applyRootMotion) {
					transform.Translate(Vector3.forward*0.05f);
				}
3.运行后，把mainCamera的“ThirdPersonCamera”组件勾除掉，以便可以拖动摄像机；
4.然后改变摄像机的位置（可以等300个角色创建好后再改位置），让摄像机只看场景的一半（拖动下x轴），接下来就是见证奇迹的时刻。
我感觉是角色跑出可视范围后，就会慢慢出问题，角色也会出现残影，最后角色都不见，这时再改变下摄像机的位置角色又出来了，但是过一会又都没了，在角色越来越少的时候，某些角色就会有残影出来。

![image](https://user-images.githubusercontent.com/14818668/39849118-6c2b42d2-543d-11e8-889b-075e8da777fd.png)
![image](https://user-images.githubusercontent.com/14818668/39849130-7633c1dc-543d-11e8-9ecb-cd2e5b8ffc6a.png)
![image](https://user-images.githubusercontent.com/14818668/39849142-7dd15080-543d-11e8-8659-c260ea6d6cdb.png)

**Comment by chbin12** [comment]
@CloudJin 我修改了一些你的代码逻辑，可以满足我的如下需求，希望对你做优化有帮助，可能我在修改中有些地方没有考虑到，希望能指正。再次感谢该项目，我已经使用在我现在的项目了，谢谢。
[AniInstancing.zip](https://github.com/Unity-Technologies/Animation-Instancing/files/2005122/AniInstancing.zip)

1.相同fbx，不同贴图的情况
2.camera，layer设置
3.实例从不可见到可见时的一些处理
4.残影的问题（感觉之前代码是个bug）

**Comment by CloudJin** [comment]
看到你添加了Frustum culling的计算，这是没必要的，因为culling group就是在做这个事情。
问题2大概是这么处理的。
问题1实际上是批次的问题，需要把不同材质的物体分为不同的批次。
问题4确实是个bug。

**Comment by chbin12** [comment]
加Frustum culling的处理是因为我发现只使用 culling group来判断时，当角色移到不可见时触发CullingStateChanged改变角色的visible为false，再移动到可见时却不会触发CullingStateChanged这个方法，也就不会改变角色的visible为true，然后该角色就不会变draw出来了,也就会出现前面我提到的角色越来越少的问题，除非改变一下摄像机的位置什么的才会再次触发CullingStateChanged

**Comment by CloudJin** [comment]
这个实际上是个bug。
在visible为false时，boundingSpere就没有更新了。导致隐藏了就再也出不来了。
最近我就会修掉的。
