### ISSUE TITLE
Animation Events triggered at wrong time

### ISSUE THREAD

**Issue by plasticcow** [Unity-Technologies/Animation-Instancing#14]
In AnimationInstance.cs method UpdateAnimationEvent() the code implies that the event time is normalised when in fact it is not.
A change to the time variable in this method is required to check the time based on actual time the animation has been running.
Making the following changes at line 403 and 407 corrected the problem for me.
float time = curFrame / info.totalFrame;
To
float time = curFrame / info.fps;

**Comment by CloudJin** [comment]
Yes, you're right. I forgot the time is not normalized time. I will fix it. Thanks for your fixing.
