### ISSUE TITLE
完善Transition遇到问题，求帮助

### ISSUE THREAD

**Issue by zhouyufan0568** [Unity-Technologies/Animation-Instancing#16]
我在自己完善Transition功能时遇到问题，当从动画A过渡到动画B，当实现动画重叠时，我需要给每个instance多提交一个原来动画的texture，就像您源码里给每个instance提交frameIndex一样，我该怎么做？

**Comment by zhouyufan0568** [comment]
谢谢您的指点

**Comment by isurfraz** [comment]
any update on transitions?
