### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by mikorigames** [Unity-Technologies/Animation-Instancing#17]
Click on "Generate" and i have this:

IndexOutOfRangeException: Array index is out of range.
AnimationInstancing.AnimationGenerator.GenerateAnimation () (at Assets/AniInstancing/Editor/AnimationGenerator.cs:114)
AnimationInstancing.AnimationGenerator.Update () (at Assets/AniInstancing/Editor/AnimationGenerator.cs:96)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.SendUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:370)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:127)

**Comment by CloudJin** [comment]
It seems the index is out of range. 
Can you upload your fbx and animations? I will check it.

**Comment by mikorigames** [comment]
Ok, this is the fbx with animations. Thanks

[https://www.dropbox.com/s/zqqufacyfzvj6s9/crowd6%40sitting_clap.fbx?dl=0](url)

**Comment by CloudJin** [comment]
I have tested your fbx and it works fine.
I think you lost something. 
Here's the prefab created by your fbx as an example. 

[TestPrefab.unitypackage.zip](https://github.com/Unity-Technologies/Animation-Instancing/files/2012011/TestPrefab.unitypackage.zip)

**Comment by mikorigames** [comment]
It doesn't work.
I have this with your prefab:

NullReferenceException: Object reference not set to an instance of an object
AnimationInstancing.AnimationManager+<LoadAnimationInfoFromAssetBundle>c__Iterator1.MoveNext () (at Assets/AniInstancing/Scripts/AnimationManager.cs:131)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by mikorigames** [comment]
Ok now it works but Mesh Animator has a better performance.

https://assetstore.unity.com/packages/tools/animation/mesh-animator-26009

**Comment by CloudJin** [comment]
Really? Maybe I need to work harder.
