### ISSUE TITLE
I keep getting index out of range errors

### ISSUE THREAD

**Issue by Athomield** [Unity-Technologies/Animation-Instancing#18]
![error](https://user-images.githubusercontent.com/7095418/40278320-3052684a-5c2f-11e8-8d50-a95cbf39fda1.PNG)
So I keep getting this error I'm not sure why. Is it the "prototype" parameter in AnimationInstance that I'm setting wrong ?
I'm using Unity 2017.3

**Comment by mikorigames** [comment]
Check if you trying to generate an animation with zero frames.

**Comment by CloudJin** [comment]
Can you upload your assets(fbx and animations)? I will check it.

**Comment by mikorigames** [comment]
Yes, i have the same problem with an animation with 0 frames
