### ISSUE TITLE
"Instancing is not supported" exception on android

### ISSUE THREAD

**Issue by pseudocolor** [Unity-Technologies/Animation-Instancing#19]
I download the project from github, try this, and its worked great on PC, 
but it didnt worked when I build the project on android, it return exception "InvalidOperationException: Instancing is not supported"

ps: I already build the assetbundle, and it wordked on unity editor

**Comment by CloudJin** [comment]
Which opengl es version is your android device?
Instancing is only supported on OpenGL es 3 or newer.

**Comment by pseudocolor** [comment]
Aah I see, thanks!

**Comment by pseudocolor** [comment]
![screenshot_2018-05-22-21-31-26](https://user-images.githubusercontent.com/10195858/40369405-6f3925fe-5dcd-11e8-8f6b-f990abc0be1b.jpg)


here is the screenshot of the exception

**Comment by CloudJin** [comment]
The device xperia z2 has adreno GPU, but the instancing only supported on OpenGL es 3.1 or newer on adreno.

**Comment by pseudocolor** [comment]
oh ok thanks for the info
