### ISSUE TITLE
Animator does not have an AnimatorController

### ISSUE THREAD

**Issue by zhouyufan0568** [Unity-Technologies/Animation-Instancing#20]
GenerateAnimation()中的workingInfo.animator.Play(workingInfo.info.animationNameHash);
每次第一个动画都会报Animator does not have an AnimatorController
我在网上查说是activeself要为true
我看见您在代码中加了workingInfo.animator.gameObject.SetActive(true);
而且调试看起来没问题。
这是为什么？

**Comment by zhouyufan0568** [comment]
我将您的代码改成：
workingInfo.animator.Update(workingInfo.length / workingInfo.info.totalFrame);
workingInfo.animator.Play(workingInfo.info.animationNameHash,0);
这样就不会报Animator does not have an AnimatorController。
看起来像是要预先执行一次Update来激活AnimatorController一样。
报Animator does not have an AnimatorController这个错误就会导致播放第一个动画时事实上播放的是AnimationController的defaultstate的动画，这样就导致第一个动画的骨骼数据其实是默认状态动画的骨骼数据。这是我测试出来的。
在前面加上：
workingInfo.animator.Update(workingInfo.length / workingInfo.info.totalFrame);
然后再正常执行代码，这样生成的骨骼数据就没问题。

**Comment by zhouyufan0568** [comment]
想问一下，当时选择骨骼数据结构时，选择了4×4旋转矩阵而没使用四元数，是不是因为GPU端计算四元数插值存在性能问题？我使用了旋转矩阵做blendtree，由于矩阵插值的原因，最终显示的效果是不对的。

**Comment by CloudJin** [comment]
实际上可以用dual Quaternion来实现蒙皮的，这样效果会更好一些，计算量会稍有增加。用矩阵的话主要是方便实现，当然蒙皮就会有些瑕疵了。

关于那个警告，感谢提供线索。我也一直奇怪为什么会有那个警告。
这里除了你说的那个问题以外，在generate的时候还漏了一帧。回头我会把fix上传的。
