### ISSUE TITLE
How is the culling supposed to work?

### ISSUE THREAD

**Issue by NumT** [Unity-Technologies/Animation-Instancing#23]
I've managed to bake my own character and am using him to visualise some pedestrian simulation data. The batching works great but what I've got now is a poly count problem. If I even slightly start to get towards having one of the crowd entities near the camera frustrum it's like I'm suddenly rendering them all - even with shadows disabled. Is this correct behaviour?

**Comment by CloudJin** [comment]
Hi, actually you need to do nothing to enable culling. 
I don't understand fully what you've got. Can you upload your demo to show the problem?
