### ISSUE TITLE
具体如何添加武器呢？

### ISSUE THREAD

**Issue by muyichun** [Unity-Technologies/Animation-Instancing#25]
您好，Attachment settings骨骼节点如何与武器绑定在一起，武器需要符合什么样的格式！
![image](https://user-images.githubusercontent.com/25608102/42408142-44aa9b0a-81fa-11e8-85cf-089c4baf108f.png)

自己尝试了，发现各种报错  
Debug.Log("Initialize animation failed. Please check out the backed animation infos.");

**Comment by CloudJin** [comment]
过几天我写个demo吧。这里确实没有说明过

**Comment by zhaocy1217** [comment]
同问怎么添加武器？？

**Comment by ares5221** [comment]
武器上的shader怎么可以使用有贴图的达到火焰那种流动波动的效果呢

**Comment by wangduoguo** [comment]
什么时候写个添加武器的教程啊，2019怎么添加都要出错

**Comment by wangduoguo** [comment]
> 过几天我写个demo吧。这里确实没有说明过

请写个2019的武器添加教程吧 attachment setting 这个用不了，出错

**Comment by iningwei** [comment]
@wangduoguo 作者README写的有！
