### ISSUE TITLE
Skinned Mesh Renderer位置方向渲染有问题

### ISSUE THREAD

**Issue by Mathbee** [Unity-Technologies/Animation-Instancing#26]
![image](https://user-images.githubusercontent.com/13581835/43079076-baf7a142-8ebe-11e8-8992-ed221355d1de.png)
![image](https://user-images.githubusercontent.com/13581835/43079085-c1608ada-8ebe-11e8-9fe7-c6443cd88723.png)
![image](https://user-images.githubusercontent.com/13581835/43109947-f00e4cb6-8f1b-11e8-9963-05633a01985a.png)

Skinned Mesh Renderer的位置和旋转不是标准位置会出现渲染出来的位置和方向出现偏移，这个是因为计算的时候只算了顶点位置的原因嘛？

**Comment by CloudJin** [comment]
你是指在scene窗口中的预览吗？那个目前是用Gizmos来画的，是有这个问题，而且也没有depth buffer。不过在运行时就没有这个问题了。
