### ISSUE TITLE
GPU Instancing draw call衔接处的网格模型没有渲染

### ISSUE THREAD

**Issue by EnigmaJJ** [Unity-Technologies/Animation-Instancing#27]
hello，我遇到个比较奇怪的问题，实例化了220个对象，发现有个对象没有被渲染，查看Frame Debugger发现是GPU Instancing draw call衔接处，请问可能是什么原因呢？
![](http://wx2.sinaimg.cn/mw690/646817c0gy1ftm4ntsb6mj20s30g67n6.jpg)

Frame Debugger的2个draw calls：
![](http://wx2.sinaimg.cn/mw690/646817c0gy1ftm4nue33jj20mn0fj0tp.jpg)
![](http://wx2.sinaimg.cn/mw690/646817c0gy1ftm4nuunryj20la0fo78z.jpg)

**Comment by CloudJin** [comment]
这看上去像是之前的一个bug。你有更新到最新的代码吗？

**Comment by EnigmaJJ** [comment]
嗯，目前是master分支最新的代码。是100%会出现的，不知道你那边测试可以复现嘛？

**Comment by ZGeng** [comment]
同样在crowd spawner demo scene里遇到这个问题

**Comment by ZGeng** [comment]
@EnigmaJJ solved in #39
