### ISSUE TITLE
系统内置的Shader应该怎么修改呢？

### ISSUE THREAD

**Issue by Mathbee** [Unity-Technologies/Animation-Instancing#30]
我直接替换人物的shader从standard成Normal-BumpSpecinstancing后，这个人物我本地该过模型的mesh的材质球，加载出来的人物与原人物不一样了。
![image](https://user-images.githubusercontent.com/13581835/43310374-fbf635ca-91b9-11e8-97d0-165a3aad60ba.png)
![image](https://user-images.githubusercontent.com/13581835/43310460-332afa4e-91ba-11e8-9afc-e0bd2258b6ce.png)

**Comment by Mathbee** [comment]
[model.zip](https://github.com/Unity-Technologies/Animation-Instancing/files/2256231/model.zip)
你这边可以留个联系方式具体交流一下问题吗？

**Comment by Mathbee** [comment]
也就是说在建模工具里面，模型处理的时候Transfrom的position不是（0，0，0），位置会有问题，rotation不是（0，0，0），旋转会有问题，scale不是（1，1，1）大小会发生变化。

**Comment by CloudJin** [comment]
@Mathbee ,我试了一下你的模型，渲染是没问题的。见图
![20180817104838](https://user-images.githubusercontent.com/31641080/44245495-7b31c780-a20b-11e8-9885-6886165913f7.png)
![20180817104925](https://user-images.githubusercontent.com/31641080/44245497-7ec54e80-a20b-11e8-9fb8-3d6481e655c9.png)

你这个模型transform是在原点的吧？

**Comment by Mathbee** [comment]
不好意思哈  可能是弄错了   我刚也试了下  确实变正常的    导致这种情况的原因可能是由于我这边之前出现了缓存或者更新代码出了问题导致的。
