### ISSUE TITLE
Shows only the first object of the animated charcter.

### ISSUE THREAD

**Issue by mastertheef** [Unity-Technologies/Animation-Instancing#38]
I have a skeleton which has such structure
Skeleton
  -- Bip (bones)
  -- Body (has skinned mesh renderer)
  -- Sword (has skinned mesh renderer)

After generation it works fine but renders only the first object which has mesh renderer. In this case Body. If I change order it will render only the sword.

**Comment by CloudJin** [comment]
sorry, I don't get it. 
What do you mean the order?
Can you give me a demo to describe the issue?

**Comment by CloudJin** [comment]
I git it. I have reproduced the issue.
I will fix it. Thanks.
