### ISSUE TITLE
Code that cause missing instancing

### ISSUE THREAD

**Issue by ZGeng** [Unity-Technologies/Animation-Instancing#39]
When switch to next package, should reset the package instancing count to 1 outside the create new condition. ( since at initial there may be more than 1 package)

https://github.com/Unity-Technologies/Animation-Instancing/blob/935207b85129aac8baa01aa55ff33dbae35b1f92/Assets/AniInstancing/Scripts/AnimationInstancingMgr.cs#L366-L367

to

   ~~```newPackage.instancingCount = 1;```~~
```
 } 
 block.packageList[aniTextureIndex][packageIndex].instancingCount = 1;
```

**Comment by CloudJin** [comment]
Yes, you're correct. I lost the that condition. 
Thanks for fixing.
