### ISSUE TITLE
Needs asset bundles?

### ISSUE THREAD

**Issue by VLukianenko** [Unity-Technologies/Animation-Instancing#40]
Does this asset needs the project to use asset bundles? Can there be an option not to use them, maybe include a path to the animation textures as a string variable or serialize them per animation converted?

**Comment by CloudJin** [comment]
In fact, if you don't build the asset bundles, the script will load the animation textures directly.

**Comment by Athomield** [comment]
Do I have to call ? Or is it just for the example ?`AnimationInstancing.AnimationManager.Instance.LoadAnimationAssetBundle(Application.streamingAssetsPath + "/AssetBundle/animationtexture") `

**Comment by CloudJin** [comment]
> Do I have to call ? Or is it just for the example ?`AnimationInstancing.AnimationManager.Instance.LoadAnimationAssetBundle(Application.streamingAssetsPath + "/AssetBundle/animationtexture")`

You don't need to call. It loads automatically.
