### ISSUE TITLE
Example keeps saying "Prototype Is NULL"

### ISSUE THREAD

**Issue by Athomield** [Unity-Technologies/Animation-Instancing#42]
While I'm trying to test the AnimInst examples (both) I keep having "The prototype is NULL. Please select the prototype first." as well as other errors. 
![rarezrezrze](https://user-images.githubusercontent.com/7095418/46952583-8e3a0a00-d08b-11e8-9a59-e374383c3474.PNG)

**Comment by Athomield** [comment]
also i have multiple skinnedmeshrendereres for one character

**Comment by CloudJin** [comment]
> While I'm trying to test the AnimInst examples (both) I keep having "The prototype is NULL. Please select the prototype first." as well as other errors.
> ![rarezrezrze](https://user-images.githubusercontent.com/7095418/46952583-8e3a0a00-d08b-11e8-9a59-e374383c3474.PNG)

Did you generate the character? If not, you should generate using Animation Generator first.

**Comment by Athomield** [comment]
I did generate the character. The problem with the example is that it did not have the prefab selected as the prototype. This has been solved. But still I can't use Animation Instancing for other issues.
