### ISSUE TITLE
Whenever I bake with attachements I get index out of range error.

### ISSUE THREAD

**Issue by Athomield** [Unity-Technologies/Animation-Instancing#43]
Whenever I try to bake animations with attachements (bone gameobjects) I get a very strange error.
![ezzeaefdser](https://user-images.githubusercontent.com/7095418/46972135-1d601580-d0be-11e8-9979-16e026699a20.PNG)
![jijpopio](https://user-images.githubusercontent.com/7095418/46972147-251fba00-d0be-11e8-8cde-c28152ab1785.PNG)
![azerezretret](https://user-images.githubusercontent.com/7095418/46972164-310b7c00-d0be-11e8-9868-c54d082508a9.PNG)

**Comment by Athomield** [comment]
This one is still persistent

**Comment by Athomield** [comment]
Does not even work with example prefab...

**Comment by ardinius** [comment]
To be very honest, i don't believe that this project works at all, i think its a dead end

**Comment by CloudJin** [comment]
have fixed.
