### ISSUE TITLE
Instancing works in editor, not in build

### ISSUE THREAD

**Issue by FarNorthEnt** [Unity-Technologies/Animation-Instancing#46]
Hello!

I have got the instancing to work in an editor scene, in which I render 100 animated models. But when I build and run the exact same scene, I first got the following error:

> Could not find a part of the path "D:\Github\FarNorthZ Bin\FarNorthZ_Data\AnimationTexture\AnimInstance.bytes".

So I simply copied the AnimationTexture folder containing the .bytes files into the FarNorthZ_Data folder. 

Now I receive no errors, and the prefab is instantiated a 100 times, just like in the editor, but there is no animation/model visible.

**Comment by FarNorthEnt** [comment]
Update:

I should add that I do this from another project. When building the example scene found in the project on this git repo, it works fine. 

The problem seems to be that the asset bundle is not loaded by default, and the game is therefor searching for the animations in the .bytes file instead.

I've tried to look in the example scene in order to find what I'm missing, but everything seems to be identical. 

1. I have an Animation Instancing Mgr attached to a game object in the scene

2. Just like the Spawner in the example, I have a script which has LoadAB() method in Start(), called in the same way. If I do not have the Load asset bundle functionality, the built application throws an error that it does not find the .bytes file. This is why I suspect I've missed something, since in another issue, you declared that the asset bundle should be loaded by default.

3. I also set use instancing to true

4. I then instantiate an enemy by using 
AnimationInstancing.AnimationInstancingMgr.Instance.CreateInstance(P_Z);

5. Again, works fine in editor, but not in build & run.

**Comment by FarNorthEnt** [comment]
Closing issue.

When I created a material from the shader I copied from this repository, I did not check "Enable GPU Instancing". If it is unchecked, for some reason, the rendering does not work when building and running.

It never occured to me that it could be the shader that caused the issue, since it worked flawlessly in the editor. Maybe someone else encounters the same issue and finds this thread useful.

Thanks for this great solution!

**Comment by Athomield** [comment]
Hi FarNorthEnt I cant seem to make this plugin work at all. What steps did you follow ? I keep getting a character in editor that is rotated and scaled falsely and many coutless errors through each step. Is there anything that is not mentionned in the blog that you have to do ? Also do you have to use asset bundles for your app or just that asset provided in the packagage ?

**Comment by FarNorthEnt** [comment]
Hello @Athomield!

I honestly can not write up all of the steps I took in order to finally get it to work. It was 8 hours of trying stuff out, and eventually it started working.

Asset bundles are part of the solution I have right now. I could not get the "automatic loading" of the instanced animations to work. However, my solution is probably not the correct way to do it either.

I'm considering examining the solution some more in order to produce a video tutorial for Youtube. If that happens, I'll let you know here.

**Comment by Athomield** [comment]
Thanks ! Also there seems to be a bug with attachements as they refuse to work altogether even in the example scene. Just a heads up !

**Comment by stevenwanhk** [comment]
HI @FarNorthEnt,

I have the exact same issue. I checked my copied material (with shader DiffuseInstancing) and "Enable GPU Instancing" is ticked. But I still experienced "Could not find a part of the path" error. Any idea for the fix? Thanks.

**Comment by stevenwanhk** [comment]
So now you could only get the build work after copying AnimationTexture folder to the build? Do we have builder for this? Thanks.
