### ISSUE TITLE
No transitions

### ISSUE THREAD

**Issue by isurfraz** [Unity-Technologies/Animation-Instancing#5]
There are no transitions for animations, this would make the system a lot more robust and usable.

Can anyone direct me on roughly what would need to be added?

**Comment by CloudJin** [comment]
The Transition is not supported for now. 
This is my next work.

**Comment by isurfraz** [comment]
any idea when you will get round to this?

 Without this it is not really a usable system in any application where visuals are important, yet with this **one** feature added, it would become one of the most amazing animation improvements to hit the unity engine! Cant explain enough how important this feature is!

**Comment by CloudJin** [comment]
sorry, I also want to implement the transitions, but some other things block me. I think I don't have time to do recently.
