### ISSUE TITLE
我测试时动作不工作

### ISSUE THREAD

**Issue by chbin12** [Unity-Technologies/Animation-Instancing#6]
你好，非常感谢能提供这个功能，我下载demo工程后直接buildassetbundle，运行工程后，角色动作正常。但是我再Animation generator一次后，再buildassetbundle，然后运行工程，角色的动作不能播放出来了，没怎么仔细看代码(ps:看不太懂:(）。用的是unity2017.2.0p3

**Comment by CloudJin** [comment]
你有看到在控制台有输出什么错误吗？
场景中什么角色都没有渲染出来吗？

**Comment by chbin12** [comment]
没有错误日志，角色渲染出来了，只是没有动作
![image](https://user-images.githubusercontent.com/14818668/39340091-b6677f94-49fe-11e8-8a0b-f20f18868a34.png)

**Comment by CloudJin** [comment]
嗯。你把你的Dude_low_instancing.bytes上传，我看一下吧。

**Comment by chbin12** [comment]
[Dude_low_instancing.bytes.zip](https://github.com/Unity-Technologies/Animation-Instancing/files/1954302/Dude_low_instancing.bytes.zip)

**Comment by CloudJin** [comment]
这确实是generator的bug。我已经commit了fix。

**Comment by chbin12** [comment]
更新后确实可以了。有个小建议，就是当animator controller如果有state没有绑motion时，generator会报错，我觉得在实际使用中，有empty state的情况。

**Comment by cg4213** [comment]
我也遇到空state的情况，不常见，但确实是有可能出现
