### ISSUE TITLE
角色为什么会没有影子？

### ISSUE THREAD

**Issue by spring315** [Unity-Technologies/Animation-Instancing#60]
制作时选中了AnimationInstancing 的ReceiveShadow， 运行起来后没有影子呢？
![QQ截图20190414235245](https://user-images.githubusercontent.com/48684171/56095651-87dcfb80-5f11-11e9-84bc-5c88be2eaaeb.png)
![QQ截图20190414234907](https://user-images.githubusercontent.com/48684171/56095652-890e2880-5f11-11e9-9fc4-e29fd6ed7eb6.png)
@CloudJin

**Comment by spring315** [comment]
制作时选中了AnimationInstancing 的ReceiveShadow， 运行起来后没有影子呢？
![QQ截图20190414234907](https://user-images.githubusercontent.com/48684171/56095604-17ce7580-5f11-11e9-845a-cf5f261e9758.png)
![QQ截图20190414235245](https://user-images.githubusercontent.com/48684171/56095605-1ac96600-5f11-11e9-86d4-c0658ba05eec.png)
@CloudJin

**Comment by CloudJin** [comment]
receive shadow是接受阴影。
要使角色产生阴影你需要改一下shadow casting mode

**Comment by Fanglouhao** [comment]
怎么改呢?

**Comment by Fanglouhao** [comment]
我瞎了
