### ISSUE TITLE
请问master，differenceMaterials 和其它的。

### ISSUE THREAD

**Issue by hsl9999** [Unity-Technologies/Animation-Instancing#67]
二个问题:
1.看到其它是以分支形式存在，是属于不稳定的吗？主干上是不是包含相关的功能？
2.List<Matrix4x4> bindPose = new List<Matrix4x4>(150);   看到代码中硬编码了 150，是说只支持到 150个骨骼矩阵吗?改大有什么问题？

**Comment by CloudJin** [comment]
1. master是稳定的，包含所有功能的主干。
2.改大也没什么问题。根据你们的需求来自己定义吧。
