### ISSUE TITLE
不能用在IOS？

### ISSUE THREAD

**Issue by cg4213** [Unity-Technologies/Animation-Instancing#7]
在bake的时候看到这个提示You can't bake animations on IOS or Android. Please switch to PC.
面向metal或者gles3的移动应用也不能用这个么？

**Comment by CloudJin** [comment]
可以用的。那句警告是指不要切换到ios或android平台来bake动画。请切到pc平台来使用animation generator。

**Comment by cg4213** [comment]
bake……这操作肯定是在编辑器跑，平台对这个过程有什么影响么？

**Comment by CloudJin** [comment]
说来惭愧，开发时在ios和android bake时有点问题；但由于时间关系，还没来得及改。以后有时间了会考虑改一下的。

**Comment by cg4213** [comment]
哦哦，可以的，能具体说一下是什么问题么？
我现在是在IOS下用Animation……历史问题
Animation的部分我会用些时间弄一弄

**Comment by CloudJin** [comment]
我也忘了为什么了。貌似打开也没什么问题。
