### ISSUE TITLE
Can shadows be disabled?

### ISSUE THREAD

**Issue by mullan7** [Unity-Technologies/Animation-Instancing#8]
So far i get okay performance, but after about 1000 low poly units the FPS starts to suffer. Profiler shows high cpu usage on animationmanager Update function. Can i improve performance by disabling shadows or possibly making it update every second frame?

**Comment by CloudJin** [comment]
You can remove "addshadow" in shader to disable shadows. 
Updating every second frame is a good idea which is needed possibly by developers. I will implement it as soon as possible.
