### ISSUE TITLE
Invisible characters on android

### ISSUE THREAD

**Issue by happypepper** [Unity-Technologies/Animation-Instancing#89]
The instancing is working fine in the unity editor, but when i test on the android device, all the characters are invisible.

Any idea what is going on?

P.s. I am using a custom shader in which I have added these lines:
```
#include    “AnimationInstancingBase.cginc”
#pragma vertex vert
```

**Comment by idyne** [comment]
Have you solve the problem?

**Comment by happypepper** [comment]
Yes I did, I didnt have GPU instancing checked on the material

**Comment by idyne** [comment]
> Yes I did, I didnt have GPU instancing checked on the material

I'm having "You should call LoadAnimationAssetBundle first." error. How can I fix it?
