### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Held0fTheWelt** [Unity-Technologies/Animation-Instancing#9]
I think, this would be a great use for my zombie assignment, but i cannot get it work.
I am using these zombies here:
https://assetstore.unity.com/packages/3d/characters/humanoids/rpg-monster-pack-27663

If i want to follow the tutorial i found here:
https://blogs.unity3d.com/2018/04/16/animation-instancing-instancing-for-skinnedmeshrenderer/

the demos work fine, but if i want to use that on my zombie, i get this:

NullReferenceException: Object reference not set to an instance of an object
AnimationInstancing.AnimationGenerator+<OnGUI>c__AnonStorey0.<>m__0 (UnityEngine.AnimationClip q) (at Assets/AniInstancing/Editor/AnimationGenerator.cs:257)
System.Collections.Generic.List`1[UnityEngine.AnimationClip].GetIndex (Int32 startIndex, Int32 count, System.Predicate`1 match) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:313)
System.Collections.Generic.List`1[UnityEngine.AnimationClip].Find (System.Predicate`1 match) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:216)
AnimationInstancing.AnimationGenerator.OnGUI () (at Assets/AniInstancing/Editor/AnimationGenerator.cs:257)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

leading me to:
                    AnimationClip clip = clips.Find(q => q.name == clipName);

What's wrong with my animation clips ???

**Comment by CloudJin** [comment]
Can you upload your fbx and animation clips? I will check.

**Comment by Held0fTheWelt** [comment]
[AxeZombie.zip](https://github.com/Unity-Technologies/Animation-Instancing/files/1976779/AxeZombie.zip)
Thanks a lot !
We need to delete it later.

**Comment by Held0fTheWelt** [comment]
[AxeZombie.zip](https://github.com/Unity-Technologies/Animation-Instancing/files/1976785/AxeZombie.zip)
Updated ... Sorry !
